# Generated by Django 4.1.4 on 2022-12-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('model', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
